# Site Settings
title: Joseph Kider
email: jkider@clemson.edu
description: >
  I am an Associate Professor at Clemson.
baseurl: ""
url: "http://127.0.0.1:4000"
twitter_username: kiderj
github_username:  hepcatjk
# Build Settings
sass:
  sass_dir: _sass
  source_map: true   # Enable source maps for Sass
include: ['_pages']
kramdown:
  input: GFM
collections:
  - publications